name = "MakieGallery"
uuid = "dbd62bd0-c9f5-5087-a2e1-f5c4bb0cec90"
version = "0.1.2"

[deps]
AbstractPlotting = "537997a7-5e4e-5d89-9595-2241ea00577e"
Base64 = "2a0f44e3-6c83-55bd-87e4-b1978d98bd5f"
BinaryProvider = "b99e7846-7c00-51b0-8f62-c81ae34c0232"
ColorSchemes = "35d6a980-a343-548e-a6ea-1d62b119f2f4"
ColorTypes = "3da002f7-5984-5a60-b8a6-cbb66c0b333f"
ColorVectorSpace = "c3611d14-8923-5661-9e6a-0046d554d3a4"
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
FFMPEG = "c87230d0-a227-11e9-1b43-d7ebe4e7570a"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
FixedPointNumbers = "53c48c17-4a7d-5ca2-90c5-79b7896eea93"
GDAL = "add2ef01-049f-52c4-9ee2-e494f65e021a"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Highlights = "eafb193a-b7ab-5a9e-9068-77385905fa72"
ImageCore = "a09fc81d-aa75-5fe9-8630-4744c3626534"
ImageFiltering = "6a3955dd-da59-5b1f-98d4-e7296123deb5"
ImageMagick = "6218d12a-5da1-5696-b52f-db25d2ecc6d1"
ImageTransformations = "02fcd773-0e25-5acc-982a-7f6622650795"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
KernelDensity = "5ab0869b-81aa-558d-bb23-cbf5423bbe9b"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
MakieLayout = "5a521ce4-ebb9-4793-b5b7-b334dfe8393c"
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
MeshIO = "7269a6da-0436-5bbc-96c2-40638cbb6118"
ModernGL = "66fc600b-dfda-50eb-8b99-91cfa97b1301"
Observables = "510215fc-4207-5dde-b226-833fc4488ee2"
OrdinaryDiffEq = "1dea7af3-3e70-54e6-95c3-0bf5283fa5ed"
ParameterizedFunctions = "65888b18-ceab-5e60-b2b9-181511a3b968"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
PlotUtils = "995b91a9-d308-5afd-9ec6-746e21dbc043"
RDatasets = "ce6b1742-4840-55fa-b093-852dadbb1d8b"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
StatsMakie = "65254759-4cff-5aa5-8326-61ce017a8c70"
SyntaxTree = "a4af3ec5-f8ac-5fed-a759-c2e80b4d74cb"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
ZipFile = "a5390f91-8eb1-5f08-bee0-b1d1ffed6cea"

[compat]
AbstractPlotting = "^0.9.16"
BinaryProvider = "0.3, 0.4, 0.5"
ColorSchemes = "3.5"
ColorTypes = "0.8, 0.9"
ColorVectorSpace = "0.8"
Colors = "0.9, 0.10, 0.11"
DataFrames = "0.20"
Distributions = "0.21, 0.22"
Documenter = "0.23, 0.24"
FFMPEG = "0.2"
FileIO = "1.1"
FixedPointNumbers = "0.6, 0.7, 0.8"
GDAL = "1"
GeometryTypes = "0.7"
Highlights = "0.4"
ImageCore = "0.8"
ImageFiltering = "0.6"
ImageMagick = "0.7, 1.1"
ImageTransformations = "0.8"
MeshIO = "0.3"
ModernGL = "1.1"
Observables = "0.2.3"
OrdinaryDiffEq = "5"
ParameterizedFunctions = "4.2"
PlotUtils = "0.6.2"
RDatasets = "0.6"
StaticArrays = "0.10, 0.11, 0.12"
StatsMakie = "0.0"
SyntaxTree = "1"
ZipFile = "0.8, 0.9"
julia = "1"

[extras]
GLFW = "f7f18e0c-5ee9-5ccd-a5bf-e8befd85ed98"
GLMakie = "e9467ef8-e4e7-5192-8a1a-b1aee30e663a"
Makie = "ee78f7c6-11fb-53f2-987a-cfe4a2b5a57a"

[targets]
test = ["GLFW", "Makie", "GLMakie"]
